INSERT INTO PUBLIC.ROLE (ROLE_NAME) VALUES ('ROLE_ADMIN');
INSERT INTO PUBLIC.ROLE (ROLE_NAME) VALUES ('ROLE_GUEST');
INSERT INTO PUBLIC.ROLE (ROLE_NAME) VALUES ('ROLE_USER');
INSERT INTO PUBLIC.MEMBER (ID, MEMBER_ID, MEMBER_NAME, MEMBER_PASSWORD) VALUES (1, 'easternpillar', 'jangdj', '1234!');
INSERT INTO PUBLIC.MEMBER_ROLES (ID, ROLE_NAME) VALUES (1, 'ROLE_ADMIN');
INSERT INTO PUBLIC.AUTHORITY (ID, AUTHORITY_NAME) VALUES (1, 'ADMIN');
INSERT INTO PUBLIC.AUTHORITY (ID, AUTHORITY_NAME) VALUES (2, 'USER');
INSERT INTO PUBLIC.AUTHORITY (ID, AUTHORITY_NAME) VALUES (3, 'GUEST');
INSERT INTO PUBLIC.ROLE_AUTHORITY (ROLE_NAME, ID) VALUES ('ROLE_ADMIN', 1);
INSERT INTO PUBLIC.ROLE_AUTHORITY (ROLE_NAME, ID) VALUES ('ROLE_ADMIN', 2);
INSERT INTO PUBLIC.ROLE_AUTHORITY (ROLE_NAME, ID) VALUES ('ROLE_USER', 2);


