INSERT INTO PUBLIC.ROLE (ROLE_NAME) VALUES ('Admin');
INSERT INTO PUBLIC.ROLE (ROLE_NAME) VALUES ('Guest');
INSERT INTO PUBLIC.ROLE (ROLE_NAME) VALUES ('User');
INSERT INTO PUBLIC.MEMBER (ID, MEMBER_ID, MEMBER_NAME, MEMBER_PASSWORD) VALUES (1, 'easternpillar', 'jangdj', 'docokko79!');
INSERT INTO PUBLIC.MEMBER_ROLES (ID, ROLE_NAME) VALUES (1, 'Admin');
INSERT INTO PUBLIC.AUTHORITY (ID, AUTHORITY_NAME) VALUES (1, 'AccessAdminPage');
INSERT INTO PUBLIC.AUTHORITY (ID, AUTHORITY_NAME) VALUES (2, 'AccessDefault');
INSERT INTO PUBLIC.ROLE_AUTHORITY (ROLE_NAME, ID) VALUES ('Admin', 1);
INSERT INTO PUBLIC.ROLE_AUTHORITY (ROLE_NAME, ID) VALUES ('Admin', 2);
INSERT INTO PUBLIC.ROLE_AUTHORITY (ROLE_NAME, ID) VALUES ('User', 2);

